prefix = "config/"
stop-words = "config/stopwords_lenient.txt"

dataset = "artist"
corpus = "line.toml"
index = "idxartist"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
