index = "idxlyrics"
corpus = "line.toml"
dataset = "lyrics"
prefix = "../config/"
stop-words = "../config/stopwords.txt"
[[analyzers]]
	filter = "default-unigram-chain"
	method = "ngram-word"
	ngram = 1
